# Generated by Django 2.1.4 on 2019-01-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=128)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('team1', models.CharField(max_length=64)),
                ('team2', models.CharField(max_length=64)),
                ('finished', models.BooleanField()),
                ('result1', models.IntegerField()),
                ('result2', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tippspiel.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.BooleanField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tippspiel.Match')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='tip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tippspiel.User'),
        ),
    ]
