# Generated by Django 2.1.4 on 2019-01-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippspiel', '0003_auto_20190113_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='finished',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
